apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-scraper
  template:
    metadata:
      labels:
        app: dummysite-scraper
    spec:
      serviceAccountName: dummysite-controller-account
      containers:
      - env:
        - name: WWW_ROOT
          value: /usr/src/app/www
        image: pasiol/dummysite-scraper@sha256:a2625c46105365404871a1ffcbf353f1b3e2b99f06c22ca30d54bb90c98cd537
        imagePullPolicy: IfNotPresent
        name: dummysite-scraper
        resources:
          limits:
            memory: "256Mi"
            cpu: "150m"
        volumeMounts:
        - mountPath: /usr/src/app/www
          name: www-data
      volumes:
        - name: www-data
          persistentVolumeClaim:
            claimName: dummysites-pvc
